### ISSUE TITLE
Discuss plan for aws@emory development and deployment

### ISSUE THREAD

**Issue by SolomonHD** [emory-libraries/avalon#78]
I have reviewed the avalon-terraform repo in detail. The changes below are what would be needed to execute this template successfully in aws@emory.
As for how to do this: We should fork the avalon-terraform repo again, this time calling our fork avalon-terraform-internal (names are not final) This would be a pubilc repo. Invite Phuong to assist in development if possible. This repo represents the public face of our efforts.

We would then create a internal/private repo called avalon-terraform-account-247, then call avalon-terraform-internal as a git submodule. This repo is were where would actually run terraform from, also secrets are stored in this repo via git crypt or some other method.

[Numbers below are the line in the code, "?" means uncertain if change needed]

### alb.tf

1 Change aws_alb to aws_lb
3 Change vpc public subnets to private subnets
6 Hard code internal as true
183 Change route53_record to reference private hosted zone instead of public
193-220 aws_alb_listener change reference of certificate_validation?
179 to EOF, redo certificate creation, will need to reference an existing cert provided in repo, most of this section will be removed 

### build.tf

75-77, unsure if this will work, references private subnets so possibly?
167 private subnets references, should work?

### cloudwatch.tf

No changes needed

### compose.tf

70-71, Can the account access SES to send email? ETA: Most of SES seems disabled, will most likely need to remove this from policy
125-127, Not sure what this section is doing, ask Phuong. ETA: I think this section is polling your current IP address (from whomever is running terraform) and adding that as an
SSH security group, it's something of a security feature. I think this should probably be removed or left wide open, possibly input a variable here.
160 Change public to private subnet
194,241 Change public to private dns
198,245 Remove file call? May be better to have the cert not have to be it's own file, just a variable
221,231,233 Change references to public fqdn? Will private hosted domain name be enough here? Or use variables to code the eventual .library.emory.edu address?
280 Change public ip to private ip

### db-avalon.tf

No changes needed

### db-fcrepo.tf

Database is postgres, there were odd aws@emory remediators that would shut down the RDS if certain parameters were not on the RDS. May need to add those conditions as a ssm_parameter

### db-setup.tf

No changes needed

### efs.tf

17 Change public subnets to private

### email.tf

I don't believe the aws@emory account allows SES, this will have to be removed or totally rewritten

### outputs.tf

Remove all references to public subnets or public ips

### s3.tf

123-127 Template creates fedora user policy and attaches it to user; not allowed in aws@emory, remove this section

### sns.tf

No changes needed but may want to expand here

### ssm.tf

No changes needed

### transcoder.tf

No changes needed

### variables.tf/.tfvars

Remove all references to public hosting names, subnets, ips

### versions.tf

No changes needed, may want to lock down provider version here

### vpc.tf

Many changes needed in this file. Currently it creates a vpc and it's subnets, not allowed in aws@emory. Instead we will be given a vpc that already exists. Will need to use rewrite module so that it will whatever vpc it's fed, then do a `terraform import aws_vpc.main.id=` command

**Comment by rotated8** [comment]
Why do we need another copy of `avalon-terraform`? Why can't we use branches?

**Comment by lovinscari** [comment]
Risk if not completed by 9/11/20 - This ticket is just discussion. SH suggest we add to this ticket the decision that needs to be completed including any discussions with Phuong. 

Work to be completed by 9/11/20 - 

- [ ] Need a decision as to Git repo (new repo or branch) - CB, AC, SH, DG to discuss and finalize plan
- [ ] Scrum team to review plan documented above to determine if all is acceptable
- [ ] Create new tickets for the actual implementation

**Comment by libdgg** [comment]
Alex, Solomon and Collin met 9/8/2020 to discuss the Git repo topic and made decisions. The result is two tickets on the board to complete the work. This addresses the first checkbox on the list above from 9/8/2020.

https://app.zenhub.com/workspaces/video-course-reserves-5f40265a5131320016940571/issues/emory-libraries/avalon/83

https://app.zenhub.com/workspaces/video-course-reserves-5f40265a5131320016940571/issues/emory-libraries/avalon/84

**Comment by SolomonHD** [comment]
I was asked to summarize my thoughts on changes needed to avalon-terraform. The goal is to get this terraform template running in aws@emory, which has restrictions on many services. The end result will be different than the original template. 

The main differences that the aws@emory version will need are:

1. ALBs are internal instead of public facing. Route 53 DNS is internal hosted zone.
2. Treat the cert as an variable that needs inputting rather than creating a cert with ACM service.
3. Do not create a VPC for each environment, rather import existing VPC into terraform.
4. All subnets changed to private, all references to Elastic IPs removed
5. Separate out transcoding server, template will have two servers per environment instead of one.
6. Make SSH security group whitelist a variable instead of trying to auto-populate
7. Remove any reference to modifying fcrepo user; user will come with proper perms.

**Comment by SolomonHD** [comment]
Closing this ticket, the terraform has been adapted to work with an aws@emory account
